### ISSUE TITLE
Issues for development environment setup

### ISSUE THREAD

**Issue by ChrGrb** [FA2021-K1/ScienceLabWebservice#1]
ToDo's for the development environment setup for the Science Lab team

* AWS
	* Request credits
	* Docker compose setup deployement
	* Create (email) account
	* ~Domain for webservice
	
* Docker Setup
	* PostgreSQL
	* React
		* Typescript
	* Apodini Server

* Github Actions
	* Build
		* NodeJS
		* Apodini
	* ~Test
	* Deployment AWS
		* Master Branch
		* ~ Development Branch for testing

**Comment by philippzagar** [comment]
Regarding the docker-compose setup and pipeline of the Apodini backend: 
Take a look at the current status of the respective files in the repo, those should be of great help for the CI/CD setup (actually, I think the only part missing is the deploy part). 
Maybe someone could even add a docker-compose develop setup for local development that starts all services except for the actual webservice, which is built and executed by XCode (therefore way more convenient and faster than to always spin up a container).
